### ISSUE TITLE
💡 [REQUEST] - Add a property to set quasar to Dark mode in the config

### ISSUE THREAD

**Issue by Seanitzel** [Maiquu/nuxt-quasar#21]
### Describe the feature

Hi!

I think it would be great if we had a way to set quasar to dark mode in the Nuxt config file.
useQuasar() returns undefined in the plugins for some reason and i am forced to do this:
```js
const quasar = useQuasar();
quasar.dark.set(true);
```

In the app.vue fie

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by Maiquu** [comment]
Will probably make it a more complete feature with being able set all plugin defaults. [How its handled in quasar.conf for plugins.](https://quasar.dev/quasar-plugins/dark#through-quasar-config-js)

**Comment by angelhdzmultimedia** [comment]
> ### Describe the feature
> Hi!
> 
> I think it would be great if we had a way to set quasar to dark mode in the Nuxt config file. useQuasar() returns undefined in the plugins for some reason and i am forced to do this:
> 
> ```js
> const quasar = useQuasar();
> quasar.dark.set(true);
> ```
> 
> In the app.vue fie
> 
> ### Additional information
> * [x]  Would you be willing to help implement this feature?
> * [ ]  Does this feature have a potential to break existing features?

There's a SSR issue with the dark mode that causes a flicker, so we can solve this 2 ways for now:

1. Disable SSR to enable SPA mode (if you don't need SSR).
2. Using `useQuasar().dark.set(true)` or  `Dark.set(true)` in `app.vue`, and as soon as the server renders the component, the dark mode will be applied, causing the flicker I mentioned.

Why in the app.vue? Because that's the first component that gets mounted. So the dark mode will be applied down the components tree.

**Comment by Maiquu** [comment]
Added with v1.4.0.

```ts
export default defineNuxtConfig({
  quasar: {
    config: {
      dark: true, // or 'auto'
    },
  },
})

Will update README in future.
