### ISSUE TITLE
Set i18n in quasar

### ISSUE THREAD

**Issue by changfeng2021** [Maiquu/nuxt-quasar#69]
### Describe the feature

hi 
I hope that after nuxt calls setLocale to change the language, quasar can also make changes, such as date picker. What should I do?

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Does this feature have a potential to break existing features?

**Comment by Maiquu** [comment]
I'm assuming you are talking about [setLocale](https://v8.i18n.nuxtjs.org/api/vue-i18n#setlocale) function from `nuxt-i18n` module. You can do something like this.

```vue
<script setup lang="ts">
import { QuasarLanguage } from 'quasar';

const { locale } = useI18n()
const { lang } = useQuasar()
const date = ref('2022/10/12')


watch(locale, async (newLocale) => {
  const pkg = await getLanguagePack(newLocale)
  lang.set(pkg)
})

async function getLanguagePack(lang: string): Promise<QuasarLanguage> {
  switch (lang) {
    case 'fr':
      return (await import(`quasar/lang/fr.mjs`)).default
    default: // fallback
      return (await import(`quasar/lang/en-US.mjs`)).default
  }
}

</script>
<template>
  <div>
    <form>
      <select v-model="locale">
        <option value="en">en</option>
        <option value="fr">fr</option>
      </select>
      <p>{{ $t('welcome') }}</p>
      <QDate v-model="date" />
    </form>
  </div>
</template>
```
Due to [limitations](https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations) of vite/rollup, you might have to enter import expression for each possible locale value.
