### ISSUE TITLE
How to import the css

### ISSUE THREAD

**Issue by irux** [Maiquu/nuxt-quasar#73]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### Environment

Nuxt project info:                                                                                                                                                      9:03:45 PM

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.16.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.6.4
- Builder:          -
- User Config:      modules, quasar, css
- Runtime Modules:  nuxt-quasar-ui@2.0.6
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                                             9:03:45 PM

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Quasar version

2.12.7

### Browsers

Google Chrome

### Description

I am trying to load css but it says it is not finding it:

 Failed to resolve import "quasar/src/css/quasar.variables.scss" 

### Reproduction steps

```bash
I have something like this:

export default defineNuxtConfig({
    modules: [
        'nuxt-quasar-ui',
    ],
    quasar: {
        cssAddon: true, sassVariables: true,
    },
    css:["quasar/src/css/quasar.variables.scss"]
})
```

**Comment by Maiquu** [comment]
There is indeed no such file at `quasar/src/css/quasar.variables.scss`. I'm not sure what you are trying to do but if you are trying to include sass variables that are used by quasar, they are already available in SFC when you enable the `sassVariables` option.

**Comment by irux** [comment]
@Maiquu What I want is to add custom scss as a new file. I have a file `app.scss` that I want to load for making defaults behavior like default `a tag decorations and so on. How can I load scss shared by all the components that is default ?`

**Comment by angelhdzmultimedia** [comment]
Can't tell if this Issue is solved or not.

Use the sassVariables option in quasar config in nuxt.config.ts passing a string with the path to the .sass file with custom variables (and I guess that setting this path will also add Quasar's built-in sass/scss variables from `quasar/src/css/quasar.variables.sass` and `quasar/src/css/quasar.variables.scss`, @Maiquu please confirm! 😅)
![image](https://github.com/Maiquu/nuxt-quasar/assets/10191085/a8483474-65bd-4959-9b49-45ce48b9a4d6)
Remember the warning about sass version: 
![image](https://github.com/Maiquu/nuxt-quasar/assets/10191085/b7920919-a183-4eb9-9921-f59ac120f5d1)

Hope this helps! 💙💚🔥👋
