### ISSUE TITLE
Loading times are slow

### ISSUE THREAD

**Issue by irux** [Maiquu/nuxt-quasar#74]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### Environment

Nuxt project info:                                                                                                                                                    10:55:52 PM

------------------------------
- Operating System: Windows_NT
- Node Version:     v18.15.0
- Nuxt Version:     3.7.4
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  npm@9.5.0
- Builder:          -
- User Config:      modules, quasar
- Runtime Modules:  nuxt-quasar-ui@2.0.6
- Build Modules:    -
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt/issues/new                                                                                                           10:55:52 PM

👉 Suggest an improvement: https://github.com/nuxt/nuxt/discussions/new

👉 Read documentation: https://nuxt.com

### Quasar version

2.12.7

### Browsers

Google Chrome

### Description

When I try to load an svg on a website, it is taking incredible slow. I was taking a look to the network tabs and it seems it loads all the possible components regardless you are using them or not. Maybe I am having an error but the same app with the same component on a SPA Vue is instantly (loading it locally not CDN or something).

 
![image](https://github.com/Maiquu/nuxt-quasar/assets/10131986/13fec77f-5a5b-48a5-89e9-cc86abaff54e)

### Reproduction steps

```bash
One example of a vue component where the image takes ages to load:

<template>
  <q-header style="color: white;" class="q-mt-md bg-transparent">
    <div class="row relative-position q-ml-auto q-mr-auto header-size">
      <q-toolbar class="bg-transparent q-px-none">
        <div class="col-lg-4 col-md-4 col-xs-8 col-sm-6">
          <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-2 col-xs-2 ">
              <q-avatar square class="full-height full-width gt-sm">
                <q-img src="~/assets/logo-black.svg"></q-img>
              </q-avatar>
            </div>
          </div>
        </div>

      </q-toolbar>
    </div>
  </q-header>
</template>
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by Maiquu** [comment]
Is it still slow when you enable the network cache?

**Comment by irux** [comment]
any news on this ? have you had this problem in the past ?

**Comment by Maiquu** [comment]
In development, I can do slight performance improvents by importing only what is used in the future. 

There is quite a bit performance penalty on initial nuxt startup when using `sassVariables` due to it compiling the entire quasar scss. You can try disabling that if you dont care about the quasar variables.

It suprised me when you say it also happens in production. Because I made sure that only components that you use are included in final bundle. And there arent many network reqyests going on production. Maybe you can provide the network waterfall for the build output as well?

I never had any issues with load times. Even now, without cache it takes like 1.5 seconds to load the page in development. Nuxt can be pretty demanding in terms of resources during development depending on project size.

**Comment by irux** [comment]
I am trying to understand what is the issue. I think it is maybe more than what I thought. Right now for example are all q-img loading slow. When I use nuxt image plugin, everything work super fast. The same happens with the q-btn. Everytime I use q-btn and I reload the page, I get it flickering/blinking and that give the feeling of the website loading super slow. Do you have any idea what can be happening ?

**Comment by valVk** [comment]
Awesome module, but load everything in the world is sad.
My browser hangs up for a while right after a page has been changed.
Besides the fact that my laptop has i7 16 Cores and 32 GB RAM.
But it is not bother me at the moment because I'm not going to go into production and I'm just using that module as an instrument for the POC. In case of production I'll stick with vanilla quasar, just tinkering with their configurations.

Again, concept which this module is providing awesome. Need some polishing

**Comment by Maiquu** [comment]
With v2.1.0, I improved performance of the module all across the board. Let me know what you think.

**Comment by Dodobibi** [comment]
I noticed the improved performance since version 1.2.0👍

**Comment by Dodobibi** [comment]
I noticed the improved performance since version 1.2.0👍
